---
title: "R Notebook"
output: github_document
---

```{r}
library(dada2)
packageVersion("dada2")
```
```{r}
path <- "/home/rstudio/octopuss/octuseq"
list.files(path)
fnFs <- sort(list.files(path, pattern="_1.fastq.gz", full.names = TRUE))
fnRs <- sort(list.files(path, pattern="_2.fastq.gz", full.names = TRUE))
sample.names <- sapply(strsplit(basename(fnFs), "_"), `[`, 1)
```
```{r}
plotQualityProfile(fnFs[1:2])
```
```{r}
plotQualityProfile(fnRs[1:2])
```

```{r}
filtFs <- file.path(path, "filtered", paste0(sample.names, "_F_filt.fastq.gz"))
filtRs <- file.path(path, "filtered", paste0(sample.names, "_R_filt.fastq.gz"))
names(filtFs) <- sample.names
names(filtRs) <- sample.names
```

```{r}
out <- filterAndTrim(fnFs, filtFs, fnRs, filtRs, truncLen=c(280,180),
              maxN=0, maxEE=c(2,2), truncQ=2, rm.phix=TRUE,
              compress=TRUE, multithread=TRUE)
head(out)
```

```{r}
errF <- learnErrors(filtFs, multithread=TRUE)
```
```{r}
errR <- learnErrors(filtRs, multithread=TRUE)
```

```{r}
plotErrors(errF, nominalQ=TRUE)
```
```{r}
plotErrors(errR, nominalQ=TRUE)
```

```{r}
dadaFs <- dada(filtFs, err=errF, multithread=TRUE)
```
```{r}
dadaRs <- dada(filtRs, err=errR, multithread=TRUE)
```
```{r}
dadaFs[[1]]
```
```{r}
mergers <- mergePairs(dadaFs, filtFs, dadaRs, filtRs, verbose=TRUE)
head(mergers[[1]])
```
```{r}
seqtab <- makeSequenceTable(mergers)
dim(seqtab)
```
```{r}
table(nchar(getSequences(seqtab)))
```

```{r}
seqtab.nochim <- removeBimeraDenovo(seqtab, method="consensus", multithread=TRUE, verbose=TRUE)
dim(seqtab.nochim)
```
```{r}
sum(seqtab.nochim)/sum(seqtab)
```
```{r}
getN <- function(x) sum(getUniques(x))
track <- cbind(out, sapply(dadaFs, getN), sapply(dadaRs, getN), sapply(mergers, getN), rowSums(seqtab.nochim))
colnames(track) <- c("input", "filtered", "denoisedF", "denoisedR", "merged", "nonchim")
rownames(track) <- sample.names
head(track)
print(sample.names)
```
```{r}
taxa <- assignTaxonomy(seqtab.nochim, "/home/rstudio/octopuss/silva_nr99_v138.1_train_set.fa.gz?download=1", multithread=TRUE)
```

```{r}
taxa.print <- taxa # Removing sequence rownames for display only
rownames(taxa.print) <- NULL
head(taxa.print)
```
```{r}
library(phyloseq); packageVersion("phyloseq")
```

```{r}
library(Biostrings); packageVersion("Biostrings")
```

```{r}
library(ggplot2); packageVersion("ggplot2")
```

```{r}
theme_set(theme_bw())
```

```{r}
donnesoctu <- read.csv("donnéesoctu.csv", sep = ",")
print(donnesoctu)
```
```{r}

donnesoctu <- read.csv("donnéesoctu.csv", sep = ",")

samples.out <- donnesoctu$Run
identifier <- substr(samples.out, 1, nchar(samples.out) - 1) 
culture <- substr(samples.out, nchar(samples.out), nchar(samples.out))

samdf <- data.frame(Identifier = identifier, Culture = culture, row.names = samples.out)

samdf <- data.frame(
  SampleName = rownames(seqtab.nochim),
  Source = c("Aqua", "Aqua", "Aqua", "Aqua", "Aqua", "Aqua", "Aqua", "Aqua", "Wild", "Wild", "Wild", "Wild", "Wild", "Wild", "Wild", "Wild", "Wild", "Wild", "Aqua", "Aqua" ) # Ajoutez les types dans l'ordre des échantillons
)
rownames(samdf) <- samdf$SampleName

if (!all(rownames(samdf) %in% rownames(seqtab.nochim))) {
  stop("Les noms d'échantillons dans samdf ne correspondent pas à ceux de seqtab.nochim")
}

ps <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows=FALSE), 
               sample_data(samdf), 
               tax_table(taxa))

print(ps)
```
```{r}
dna <- Biostrings::DNAStringSet(taxa_names(ps))
names(dna) <- taxa_names(ps)
ps <- merge_phyloseq(ps, dna)
taxa_names(ps) <- paste0("ASV", seq(ntaxa(ps)))
ps
```
```{r}
plot_richness(ps, measures=c("Shannon", "Simpson"))
```

```{r}
ps.prop <- transform_sample_counts(ps, function(otu) otu/sum(otu))
ord.nmds.bray <- ordinate(ps.prop, method="NMDS", distance="bray")
```

```{r}
sum(is.na(otu_table(ps.prop)))
str(ps.prop)
ps.prop <- subset_samples(ps.prop, !is.na(otu_table(ps.prop)))
otu_table(ps.prop)[is.na(otu_table(ps.prop))] <- rowMeans(otu_table(ps.prop), na.rm = TRUE)
```

```{r}
ord.nmds.bray <- ordinate(ps.prop, method = "NMDS", distance = "bray")
```

```{r}
plot_ordination(ps.prop, ord.nmds.bray, title="Bray NMDS")
```

```{r}
top20 <- names(sort(taxa_sums(ps), decreasing=TRUE))[1:3000]
ps.top20 <- transform_sample_counts(ps, function(OTU) OTU/sum(OTU))
ps.top20 <- prune_taxa(top20, ps.top20)
plot_bar(ps.top20, fill = "Phylum") + facet_wrap(~Source, scales="free_x")
theme_bw()

```
```{r}
library(ggplot2)

data <- data.frame(
  Sample = rep(c("Aqua", "Wild"), each = 10),
  Phylum = rep(c("Proteobacteria", "Bacteroidota", "Firmicutes", "Actinobacteriota",
                 "Chloroflexi", "Verrucomicrobiota", "Planctomycetota", "Myxococcota", 
                 "SAR324", "Other"), 2),
  Abundance = c(runif(10, 0.01, 0.25), runif(10, 0.01, 0.25))
)

ggplot(data, aes(x = Sample, y = Abundance, fill = Phylum)) +
  geom_bar(stat = "identity", position = "stack") +  
  labs(
    title = "Répartition des phylums microbiens",
    x = "Échantillons",
    y = "Abondance relative"
  ) +
  theme_bw()

```
```{r}
library(ggplot2)
library(viridis)  

plot_bar(ps.top20, fill = "Phylum") +
  facet_wrap(~Source, scales = "free_x") +  # Facettes par Source
  geom_bar(stat = "identity", color = "white", size = 0.2) +  
  scale_fill_viridis_d(option = "plasma", name = "Phylum") +  
  labs(
    title = "Abondance relative des Phylums microbiens",
    x = "Échantillons",
    y = "Abondance relative"
  ) +
  theme_minimal() +  
  theme(
    text = element_text(size = 12),  # Taille générale des textes
    axis.text.x = element_text(angle = 45, hjust = 1, size = 10),  # Rotation des étiquettes X
    legend.key.size = unit(0.5, "cm"),  
    legend.position = "right",  
    panel.grid.major = element_blank(),  
    panel.grid.minor = element_blank()   
  )

```


```{r}
richness_div <- estimate_richness(ps, measures = c("Observed", "Shannon", "Simpson", "Chao1"))

richness_div$Source <- sample_data(ps)$Source

head(richness_div)
```

```{r}
# Test de significativité pour Chao1
chao_test <- wilcox.test(Chao1 ~ Source, data = richness_div)

chao_label <- ifelse(chao_test$p.value < 0.05, "*", "NS")

# Graphique pour l'indice Chao1
ggplot(richness_div, aes(x = Source, y = Chao1, fill = Source)) +
  geom_violin(trim = FALSE) + 
  geom_boxplot(width = 0.1, outlier.shape = NA) +  
  labs(title = "Indice Chao1", 
       x = "Groupe", 
       y = "Indice Chao1") +
  scale_fill_manual(values = c("Aqua" = "#9999FF", "Wild" = "#FF9999")) +   
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +  # Rotation des labels de l'axe x
  scale_x_discrete(limits = c("Wild", "Aqua")) +  
  geom_text(x = 1.5, y = max(richness_div$Chao1) + 0.1, label = chao_label, size = 5)
```
```{r}
# Test de Wilcoxon pour la richesse observée (Observed)
observed_test <- wilcox.test(Observed ~ Source, data = richness_div)
observed_label <- ifelse(observed_test$p.value < 0.05, "*", "NS")

ggplot(richness_div, aes(x = Source, y = Observed, fill = Source)) +
  geom_violin(trim = FALSE) +  # Crée un graphique en violon
  geom_boxplot(width = 0.1, outlier.shape = NA) +  # Ajoute une boîte à moustaches
  labs(title = "Richesse Observée", 
       x = "Groupe", 
       y = "Richesse Observée") +
  scale_fill_manual(values = c("Aqua" = "#9999FF", "Wild" = "#FF9999")) +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +  
  scale_x_discrete(limits = c("Wild", "Aqua")) +  
  geom_text(x = 1.5, y = max(richness_div$Observed) + 0.1, label = observed_label, size = 5)
```

```{r}
# Test de significativité pour Shannon
shannon_test <- wilcox.test(Shannon ~ Source, data = richness_div)

shannon_label <- ifelse(shannon_test$p.value < 0.05, "*", "NS")

# Graphique en violon pour la richesse observée (Shannon)
ggplot(richness_div, aes(x = Source, y = Shannon, fill = Source)) +
  geom_violin(trim = FALSE) +  # Crée un graphique en violon
  geom_boxplot(width = 0.1, outlier.shape = NA) +  # Ajoute une boîte à moustaches
  labs(title = "Diversity Alpha (Indice de Shannon)", 
       x = "Groupe", 
       y = "Indice de Shannon") +
  scale_fill_manual(values = c("Aqua" = "#9999FF", "Wild" = "#FF9999")) +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +  
  scale_x_discrete(limits = c("Wild", "Aqua")) +  
  geom_text(x = 1.5, y = max(richness_div$Shannon) + 0.1, label = shannon_label, size = 5)
```


```{r}
library(ggplot2)

# Test de Wilcoxon pour Simpson
simpson_test <- wilcox.test(Simpson ~ Source, data = richness_div)

simpson_label <- ifelse(simpson_test$p.value < 0.05, "*", "NS")

y_position <- max(richness_div$Simpson, na.rm = TRUE) + 0.1  

# Graphique en violon pour l'indice Simpson
ggplot(richness_div, aes(x = Source, y = Simpson, fill = Source)) +
  geom_violin(trim = FALSE) +  # Crée un graphique en violon
  geom_boxplot(width = 0.1, outlier.shape = NA) +  # Ajoute une boîte à moustaches
  labs(title = "Indice Simpson", 
       x = "Groupe", 
       y = "Indice Simpson") +
  scale_fill_manual(values = c("Aqua" = "#9999FF", "Wild" = "#FF9999")) + 
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +  
  scale_x_discrete(limits = c("Wild", "Aqua")) +  
  geom_text(aes(x = 1.5, y = y_position, label = simpson_label), size = 5)
```


```{r}

install.packages("circlize")

library(circlize)
```


```{r}
bray_curtis_dist <- phyloseq::distance(ps, method = "bray")
ord_pcoa <- ordinate(ps, method = "PCoA", distance = bray_curtis_dist)
pcoa_data <- data.frame(ord_pcoa$vectors)
# Extraire la variance expliquée par chaque axe
eig_values <- ord_pcoa$values$Relative_eig
pc1_variance <- round(100 * eig_values[1], 1)
pc2_variance <- round(100 * eig_values[2], 1)
colnames(pcoa_data)[1:2] <- c("MDS1", "MDS2")
pcoa_data$Source <- as.factor(sample_data(ps)$Source)
library(ggplot2)

ggplot(pcoa_data, aes(x = MDS1, y = MDS2, color = Source)) + 
  geom_point(size = 4) +  # Points pour chaque échantillon
  labs(
    title = paste("PCoA de la Diversité Bêta - PC1: ", pc1_variance, "%, PC2: ", pc2_variance, "%"),
    x = paste("PCoA1 (", pc1_variance, "%)", sep = ""),
    y = paste("PCoA2 (", pc2_variance, "%)", sep = "")
  ) + 
  scale_color_manual(values = c("Aqua" = "#9999FF", "Wild" = "#FF9999")) +  
  theme_minimal()  

```


```{r}
# Charger les bibliothèques nécessaires
library(phyloseq)
library(ggplot2)
library(pheatmap)

ps_normalized <- transform_sample_counts(ps, function(otu) otu / sum(otu))

otu_matrix <- as.matrix(otu_table(ps_normalized))
rownames(otu_matrix) <- paste0("ASV", seq_len(nrow(otu_matrix)))  


top_OTUs <- names(sort(taxa_sums(ps), decreasing = TRUE))[1:20]
otu_top_matrix <- otu_matrix[top_OTUs, ]

pheatmap(otu_top_matrix,
         cluster_rows = TRUE,
         cluster_cols = TRUE,
         scale = "row",
         show_rownames = TRUE,
         show_colnames = TRUE,
         color = colorRampPalette(c("blue", "white", "red"))(50),
         main = "Heatmap des 20 OTUs les plus abondants")


```
```{r}
plot_heatmap(ps_normalized, method = "NMDS", distance = "bray")
```

```{r}
 plot_heatmap(ps_normalized, method = "NMDS", distance = "bray", 
               taxa.label = "Genus", taxa.order = "Genus", 
               low="beige", high="red", na.value="beige")
```







